### ISSUE TITLE
File path handling in ISA-TAB files

### ISSUE THREAD

**Issue by vedina** [ISA-tools/ISAcreator#245]
Two issues when selecting data files in ISACreator

1) In Windows the file delimiter disappears, and the data file columns contain string like

C:ToxBankISAcreator.SEURAT-v1.7.2ISAcreator.SEURATisatab filesFILENAME.data

2) We would like to avoid using the full path name, and use the relative path instead (the files are in the same folder as i__.txt, s__.txt and a_*.txt files). The full paths (as on the client computer) are not useful when uploading the ISA-TAB archive to a server; but currently we are not aware how to ensure relative paths in ISACreator (other than editing the ISA-TAB files in an external spreadsheet editor).

**Comment by djcomlab** [comment]
Issue (1) has cropped up again with a few other users, and I can reproduce this bug on Windows 10. Happens when you save an ISA-Tab, then reload it later. I am guessing it's something to do with the `\` backslash perhaps being interpreted as an escape when loading and being ignored.

Will investigate.

**Comment by djcomlab** [comment]
After some investigation, I have found this is a more general problem as I can reproduce this on MacOSX.

Backslashes that are unescaped, such as `\\`, render in the study/assay sheet GUI as a single backslash `\`.  Single slashes, such as `\`, disappear. An unwanted side affect is that even if strings with `\\`are loaded, because they are rendered as `\`, on a following save-and-load, the slash will disappear.

The problem is the slashes being stripped when loading from file, and not when saving.

**Comment by djcomlab** [comment]
Further investigation finds that `opencsv` `CSVReader` that is used in `SpreadsheetImport.java` interprets `\` as an escape character on read.

**Comment by djcomlab** [comment]
Fix will be available in upcoming release of ISAcreator 1.7.10.
