### ISSUE TITLE
The app doesn't work with Java 9

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/ISAcreator#324]
After selection of mode (light/std/genome) the app stops and asks to upgrade to the latest version of Java

**Comment by djcomlab** [comment]
Hi Hanna, can you confirm which OS as well you're using?

**Comment by hcwi** [comment]
Hi David!
macOS High Sierra

**Comment by djcomlab** [comment]
OK thanks! Actually I just tested in Ubuntu 16.04 also, and that splash screen that you described about unsupported Java version also comes up...

**Comment by djcomlab** [comment]
I think maybe the way Java 9 reports its version in the system environment has changed, so the code that checks a minimum Java version for ISAcreator incorrectly thinks Java 9 is too old.

i.e.

Java 8 as an environment variable `java.version `is `1.8.x`
Java 9 as an environment variable `java.version `is `9.x.x`

and the startup code in ISAcreator parses `java.version` and looks at the second minor version number instead of the major version number that Java may have changed convention to using, thus incorrectly causing this stop condition.
